name: Python Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: ["main"]
    paths:
      - "**.py"
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install dependencies
        # run: pip install flake8
        run: pip install -r requirements.txt
      - name: Add Problem Matcher
        run: |
          echo "::add-matcher::.github/flake8_error.json"
          echo "::add-matcher::.github/flake8_error.json"
          echo "::add-matcher::.github/mypy_error.json"
      - name: flake8
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=127 --ignore=E226,W503
      - name: mypy
        run: |
          mypy .
