name: Python Lint

on:
  pull_request:
    types: [opened, synchronize]
    branches: ["main"]
    paths:
      - "**.py"
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: |
          flake8 . --max-complexity=10 --max-line-length=90
