name: Python Testing

on:
  pull_request:
    types: [opened, synchronize]
    branches: ["main"]
    paths:
      - "**.py"
jobs:
  flake8:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install flake8 & mypy
        run: pip install flake8 mypy
      - name: Add Problem Matcher
        run: |
          echo "::add-matcher::.github/lint_error.json"
      - name: Run flake8
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=127 --ignore=E226,W503
      - name: Run mypy
        run: |
          mypy .
